CREATE TABLE `teachers` (
    `teacher_id` CHAR(10) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `is_editor` TINYINT(1) UNSIGNED NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`teacher_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;